modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/Cubenyx-Studio/minecraft-overlay/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"
displayURL = "https://github.com/Cubenyx-Studio/minecraft-overlay"
logoFile = "logo.png"

[[dependencies.minecraftoverlay]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.minecraftoverlay]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,1.22)"
ordering = "NONE"
side = "CLIENT"

